### ISSUE TITLE
Use this package on server-side ?

### ISSUE THREAD

**Issue by 0gust1** [rcsb/rcsb-api-tools#1]
Hi,

Thanks a lot for this package! 

We have some trouble to make it work on an server-side environment (as the GraphQLRequest is unaware that we work in a server-side env where a fetch polyfill is already available). 

We're interested to use `rcsb-api-tools` mostly because of the types that comes with lib and also by the tight integration with RCSB's APIs.

Our project is a sveltekit-based app. In dev-mode everything runs OK, but in production mode, we have the following error:

> Error: fetch is not found globally and no fetcher passed, to fix pass a fetch for your environment like https://www.npmjs.com/package/node-fetch. For example: import fetch from 'node-fetch'; import { createHttpLink } from 'apollo-link-http'; const link = createHttpLink({ uri: '/graphql', fetch: fetch });

As far as we understand, we have the following solutions:
1. one solution (on your side) could be to extend the options and APIs of the objects exposed by `rcsb-api-tools` to let the user have more control over the graphQL client initialization and pass a fetcher instance (as it is hinted by the error message)
2. another solution (on your side) could be for you to publish the sources in the npm package (`src/` folder). In our opinion, we have the error because our app consumes the built package `node_modules/@rcsb/rcsb-api-tools/build/RcsbGraphQL/GraphQLRequest.js`. This "module" is commonJS code wrapped by webpack, and seems unable to detect that we have a `fetch` instance defined globally.
If the package exposed source typescript files, our build system would use them and we bet we would not have this problem.  
Another sub-solution (on your side) could be to expose true ESM modules (instead of webpack-wrapped ones), but we acknowledge again that it's not an easy topic nowadays (modules format and JS ecosystem...)
3. another solution (on our side) could be to use the types in `rcsb-api-tools` but not the lib by itself. It is the "by default" solution for us.
4. maybe we don't use the right package and should use another ? Let us know if it's the case.

**Comment by bioinsilico** [comment]
Thank you, @0gust1 for your interested on this library and helping us to improve it. I have exposed the  `ApolloClient` configuration through and optional parameter of `GraphQLRequest` class. You should be able to provide an external fetch function now. In addition, the `SearchRequest` class also accepts a fetch-like function as optional parameter. Let me know if that fix your problem.

**Comment by 0gust1** [comment]
Many thanks, we did the test, and the version you pushed seems to do the job on our case.

In our case – a svelte-kit app using the graphQL client in an endpoint (server-side code) – we simply passed the `fetch` instance exposed internally by svelte-kit to `GraphQLRequest `:
`const RCSBGraphQLClient = new GraphQLRequest('borrego',{fetch: fetch});`

Thanks again and best wishes for you and your team !

**Comment by bioinsilico** [comment]
Thank you, @0gust1 . Let me know if any other issue arises.
